In [15]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [16]:
!wget https://archive.ics.uci.edu/static/public/222/bank+marketing.zip
!unzip -o bank+marketing.zip
!unzip -o bank.zip

--2024-10-17 01:13:13--  https://archive.ics.uci.edu/static/public/222/bank+marketing.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘bank+marketing.zip.4’

bank+marketing.zip.     [   <=>              ] 999.85K  2.06MB/s    in 0.5s

2024-10-17 01:13:13 (2.06 MB/s) - ‘bank+marketing.zip.4’ saved [1023843]

Archive:  bank+marketing.zip
 extracting: bank.zip
 extracting: bank-additional.zip
Archive:  bank.zip
  inflating: bank-full.csv
  inflating: bank-names.txt
  inflating: bank.csv

In [17]:
bank_data = pd.read_csv('bank-full.csv', sep=';')
bank_data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [18]:
bank_data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [19]:
bank_data_columns = ['age','job','marital','education','balance','housing','loan','contact','day','month','duration','campaign','pdays','previous','poutcome','y']
bank_data = bank_data[bank_data_columns]
bank_data.head()

,age,job,marital,education,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [20]:
print('Question 1. Mode for the column `education`')
print()
print(bank_data.education.groupby(bank_data.education).count().sort_values(ascending=False).head(1))

Question 1. Mode for the column `education`

education
secondary    23202
Name: education, dtype: int64

In [21]:
bank_data_numerical_col = bank_data.columns[bank_data.dtypes == 'int64']
bank_data[bank_data_numerical_col]

       age  balance  day  duration  campaign  pdays  previous
0       58     2143    5       261         1     -1         0
1       44       29    5       151         1     -1         0
2       33        2    5        76         1     -1         0
3       47     1506    5        92         1     -1         0
4       33        1    5       198         1     -1         0
...    ...      ...  ...       ...       ...    ...       ...
45206   51      825   17       977         3     -1         0
45207   71     1729   17       456         2     -1         0
45208   72     5715   17      1127         5    184         3
45209   57      668   17       508         4     -1         0
45210   37     2971   17       361         2    188        11

[45211 rows x 7 columns]

In [22]:
bank_data_corr_matrix = bank_data[bank_data_numerical_col].corr()
print()
print("Matrix correlation")
print(bank_data_corr_matrix)
bank_data_corr_list =  [['age and balance',bank_data_corr_matrix['age']['balance']]]
bank_data_corr_list += [['day and campaing',bank_data_corr_matrix['day']['campaign']]]
bank_data_corr_list += [['day and pdays',bank_data_corr_matrix['day']['pdays']]]
bank_data_corr_list += [['pdays and previous',bank_data_corr_matrix['pdays']['previous']]]
print()
print("Question 2. Two features with the biggest correlation")
print()
bank_data_corr_list.sort(reverse=True)
bank_data_corr_list[0]

Matrix correlation
               age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

Question 2. Two features with the biggest correlation

['pdays and previous', 0.4548196354805043]

In [23]:
bank_data_copy = bank_data.copy()

In [24]:
bank_data_copy.y = bank_data_copy.y.map({'yes': 1, 'no': 0})
bank_data_copy.head()

,age,job,marital,education,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,0
1,44,technician,single,secondary,29,yes,no,unknown,5,may,151,1,-1,0,unknown,0
2,33,entrepreneur,married,secondary,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,0
3,47,blue-collar,married,unknown,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,0
4,33,unknown,single,unknown,1,no,no,unknown,5,may,198,1,-1,0,unknown,0

In [25]:
from sklearn.model_selection import train_test_split

bd_train_full, bd_test = train_test_split(bank_data_copy, test_size=0.2, random_state=42)
bd_train, bd_val = train_test_split(bd_train_full, test_size=0.25, random_state=11)

len(bank_data_copy),len(bd_train)+len(bd_val)+len(bd_test)

y_train = bd_train.y.values
y_val = bd_val.y.values
y_test = bd_test.y.values

del bd_train['y']
del bd_val['y']
del bd_test['y']

bd_train.head()

,age,job,marital,education,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
27005,37,housemaid,divorced,secondary,1040,yes,no,cellular,21,nov,567,1,184,1,other
32891,30,services,single,secondary,732,yes,no,cellular,17,apr,358,2,-1,0,unknown
22101,58,retired,married,primary,358,no,no,cellular,21,aug,396,2,-1,0,unknown
7622,29,management,married,tertiary,1671,yes,no,unknown,30,may,182,1,-1,0,unknown
32115,30,services,married,secondary,292,yes,yes,cellular,15,apr,651,4,-1,0,unknown

In [26]:
from sklearn.metrics import mutual_info_score

bank_data_categorical_col = bd_train.columns[bd_train.dtypes == 'object']
bank_data_categorical_col

def mutual_info_y_score(series):
    return round(mutual_info_score(series, y_train),2)

bd_mi = bd_train[bank_data_categorical_col].apply(mutual_info_y_score)
bd_mi = bd_mi.sort_values(ascending=False)

print('Question 3. Variable with the biggest mutual information score')
print()
bd_mi

Question 3. Variable with the biggest mutual information score

month        0.03
poutcome     0.03
job          0.01
housing      0.01
contact      0.01
marital      0.00
education    0.00
loan         0.00
dtype: float64

In [27]:
from sklearn.feature_extraction import DictVectorizer

bd_train.reset_index(drop=True, inplace=True)
bd_val.reset_index(drop=True, inplace=True)
bd_test.reset_index(drop=True, inplace=True)

bd_cols = bank_data_categorical_col.tolist() + bank_data_numerical_col.tolist()

train_dict = bd_train[bd_cols].to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dict)

X_train.shape

X_train[0]

array([3.70e+01, 1.04e+03, 1.00e+00, 1.00e+00, 0.00e+00, 0.00e+00,
       2.10e+01, 5.67e+02, 0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
       0.00e+00, 1.84e+02, 0.00e+00, 1.00e+00, 0.00e+00, 0.00e+00,
       1.00e+00])

In [28]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [29]:
val_dict = bd_val[bd_cols].to_dict(orient='records')
X_val = dv.transform(val_dict)

y_pred = model.predict_proba(X_val)[:, 1]

model_accuracy = (y_val == (y_pred >= 0.5)).mean()
model_accuracy

print('Question 4. Accuracy on the validation dataset')
print()
print(round(model_accuracy,2))

Question 4. Accuracy on the validation dataset

0.9

In [30]:
model_accuracy_diff = []

for col in bd_train.columns:
    print('Train without column: ',col)
    print()
    bd_train_copy = bd_train.copy()
    bd_val_copy = bd_val.copy()

    bd_train_copy.drop(col, axis=1, inplace=True)
    bd_val_copy.drop(col, axis=1, inplace=True)

    train_dict = bd_train_copy[bd_train_copy.columns].to_dict(orient='records')
    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(train_dict)

    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    val_dict = bd_val_copy[bd_val_copy.columns].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    y_pred = model.predict_proba(X_val)[:, 1]

    model_accuracy_col = (y_val == (y_pred >= 0.5)).mean()

    print("Model accuracy all columns is:",round(model_accuracy,5))
    print("Model accuracy without column", col, "is:",round(model_accuracy_col,5))
    print("Diff:", round(model_accuracy - model_accuracy_col,5))
    print()

    if col in ['age','balance','marital','previous']:
      model_accuracy_diff.append([col,round(model_accuracy - model_accuracy_col,5)])

print('Question 5. Feature with the smallest difference')
print()
print(model_accuracy_diff)

Train without column:  age

Model accuracy all columns is: 0.90268
Model accuracy without column age is: 0.90223
Diff: 0.00044

Train without column:  job

Model accuracy all columns is: 0.90268
Model accuracy without column job is: 0.90179
Diff: 0.00088

Train without column:  marital

Model accuracy all columns is: 0.90268
Model accuracy without column marital is: 0.9019
Diff: 0.00077

Train without column:  education

Model accuracy all columns is: 0.90268
Model accuracy without column education is: 0.90246
Diff: 0.00022

Train without column:  balance

Model accuracy all columns is: 0.90268
Model accuracy without column balance is: 0.90345
Diff: -0.00077

Train without column:  housing

Model accuracy all columns is: 0.90268
Model accuracy without column housing is: 0.90113
Diff: 0.00155

Train without column:  loan

Model accuracy all columns is: 0.90268
Model accuracy without column loan is: 0.90246
Diff: 0.00022

Train without column:  contact

Model accuracy all columns is: 0.90268
Model accuracy without column contact is: 0.90212
Diff: 0.00055

Train without column:  day

Model accuracy all columns is: 0.90268
Model accuracy without column day is: 0.90168
Diff: 0.001

Train without column:  month

Model accuracy all columns is: 0.90268
Model accuracy without column month is: 0.90046
Diff: 0.00221

Train without column:  duration

Model accuracy all columns is: 0.90268
Model accuracy without column duration is: 0.8914
Diff: 0.01128

Train without column:  campaign

Model accuracy all columns is: 0.90268
Model accuracy without column campaign is: 0.90157
Diff: 0.00111

Train without column:  pdays

Model accuracy all columns is: 0.90268
Model accuracy without column pdays is: 0.90223
Diff: 0.00044

Train without column:  previous

Model accuracy all columns is: 0.90268
Model accuracy without column previous is: 0.90234
Diff: 0.00033

Train without column:  poutcome

Model accuracy all columns is: 0.90268
Model accuracy without column poutcome is: 0.89493
Diff: 0.00774

Question 5. Feature with the smallest difference

[['age', 0.00044], ['marital', 0.00077], ['balance', -0.00077], ['previous', 0.00033]]

In [31]:
model_accuracy_array=[]

train_dict = bd_train[bd_train.columns].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dict)

val_dict = bd_val[bd_val.columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

for r in [0.01,0.1,1,10,100]:
  model = LogisticRegression(solver='liblinear', C=r, max_iter=1000, random_state=42)
  model.fit(X_train, y_train)

  y_pred = model.predict_proba(X_val)[:, 1]

  model_accuracy_r = round((y_val == (y_pred >= 0.5)).mean(),3)
  model_accuracy_array.append([r,model_accuracy_r ])

print('Question 6. Smallest `C` that leads to the best accuracy on the validation set')
print()
print(model_accuracy_array)

Question 6. Smallest `C` that leads to the best accuracy on the validation set

[[0.01, 0.9], [0.1, 0.902], [1, 0.903], [10, 0.903], [100, 0.902]]